BloodBank1/Models/DonationDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BloodBank1.Models
{
    public class DonationDetail
    {
        public int r_id { get; set; }
        public string r_fullname { get; set; }
        public DateTime r_dob { get; set; }
        public string r_gender { get; set; }
        public string r_contact_number { get; set; }
        public string r_city { get; set; }
        public DateTime r_date_recieved { get; set; }
        public int blood_id { get; set; }
        public string blood_type { get; set; }
        public int unit_of_blood { get; set; }
        public DateTime d_date_donated { get; set; }
        public DateTime expiry_date { get; set; }
        public int d_id { get; set; }
        public string d_firstname { get; set; }
        public string d_lastname { get; set; }
        public DateTime d_dob { get; set; }
        public string d_gender { get; set; }
        public DateTime d_last_date_donation { get; set; }
        public string d_city { get; set; }
        public string d_contact_number { get; set; }
        public string d_email_id { get; set; }
        public string d_address { get; set; }
    }
}

BloodBank1/Controllers/BankBloodController.cs
using BloodBank1.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace BloodBank1.Controllers
{
    public class BankBloodController : Controller
    {
        private readonly ILogger<BankBloodController> _logger;
        HttpClient httpClient = new HttpClient();
        string basePath = "https://localhost:44353/";

        // 200 OK
        // 400 Bad Request
        // 500 Internal Server Error

        public BankBloodController(ILogger<BankBloodController> logger)
        {
            _logger = logger;
        }

        private string GetSession()
        {
            string check_Session = HttpContext.Session.GetString("Login_Session");
            return check_Session;
        }

        [HttpGet]
        public IActionResult Index()
        {
            string check_Session = GetSession();
            if (check_Session == null || check_Session == "")
            {
                TempData["errorMsg"] = "Unauthorized Login to Continue";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                try
                {
                    var dataFetched = httpClient.GetStringAsync(basePath + "getBank2BloodStock").Result;
                    dynamic jsonObject = JsonConvert.DeserializeObject(dataFetched);

                    long total_blood = 0;
                    foreach (var obj in jsonObject)
                    {
                        string blood_type = obj.bloodType;
                        total_blood += (int)obj.units;

                        ViewData[blood_type] = obj.units;
                    }
                    ViewData["total_blood"] = total_blood;

                    return View();
                }
                catch
                {
                    return RedirectToAction("ErrorPage", "Dashboard");
                }
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BloodBank1/Controllers/DashboardController.cs
using BloodBank1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Data;
using System.Net.Http.Headers;
using System.Text;
using System.Net;

namespace BloodBank1.Controllers
{
    public class DashboardController : Controller
    {
        private readonly ILogger<DashboardController> _logger;
        HttpClient httpClient = new HttpClient();
        string basePath = "https://localhost:44353/";

        // 200 OK
        // 400 Bad Request
        // 500 Internal Server Error

        public DashboardController(ILogger<DashboardController> logger)
        {
            _logger = logger;
        }

        private string GetSession()
        {
            string check_Session = HttpContext.Session.GetString("Login_Session");
            return check_Session;
        }

        // Dashboard Home Page
        [HttpGet]
        public IActionResult Index()
        {
            string check_Session = GetSession();
            if (check_Session == null || check_Session == "")
            {
                TempData["errorMsg"] = "Unauthorized Login to Continue";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                try
                {
                    var dataFetched = httpClient.GetStringAsync(basePath + "getBloodStock").Result;
                    dynamic jsonObject = JsonConvert.DeserializeObject(dataFetched);

                    long total_blood = 0;
                    foreach (var obj in jsonObject)
                    {
                        string blood_type = obj.blood_type;
                        total_blood += (int)obj.total_units;

                        ViewData[blood_type] = obj.total_units;
                    }
                    ViewData["total_blood"] = total_blood;

                    return View();
                }
                catch
                {
                    return RedirectToAction("ErrorPage", "Dashboard");
                }
            }
        }

        // Logout and Clear Session
        public IActionResult Logout()
        {
            string check_Session = GetSession();
            if (check_Session == null || check_Session == "")
            {
                TempData["errorMsg"] = "Unauthorized Login to Continue";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                try
                {
                    HttpContext.Session.Remove("Login_Session");
                    return RedirectToAction("Index", "Home");
                }
                catch
                {
                    return RedirectToAction("ErrorPage", "Dashboard");
                }
            }
        }

        // Error Page View
        public IActionResult ErrorPage() => View();

        // New Donor Page View
        public IActionResult NewDonor()
        {
            string check_Session = GetSession();
            if (check_Session == null || check_Session == "")
            {
                TempData["errorMsg"] = "Unauthorized Login to Continue";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View();
            }
        }

        // Add new Donor on Submit from NewDonor() View
        [HttpPost]
        public IActionResult NewDonorAdd(Donor donor)
        {
            string check_Session = GetSession();
            if (check_Session == null || check_Session == "")
            {
                TempData["errorMsg"] = "Unauthorized Login to Continue";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                try
                {
                    httpClient.BaseAddress = new Uri(basePath);
                    httpClient.DefaultRequestHeaders.Accept.Clear();
                    httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    //HTTP POST
                    var stringContent = new StringContent(JsonConvert.SerializeObject(donor), Encoding.UTF8, "application/json");
                    var postTask = httpClient.PostAsync(basePath + "addNewDonor", stringContent);

                    var result = postTask.Result;
                    if (result.StatusCode == HttpStatusCode.OK)
                    {
                        TempData["msgHead"] = "Success";
                        TempData["msgBody"] = "Added New Donor Data to BoodBank...!";
                        return RedirectToAction("NewDonor", "Dashboard");
                    }
                    else
                    {
                        TempData["msgHead"] = "Failed";
                        TempData["msgBody"] = "Unable to Add New Donor Data...!";
                        return RedirectToAction("NewDonor", "Dashboard");
                    }
                }
                catch
                {
                    return RedirectToAction("ErrorPage", "Dashboard");
                }
            }
        }

        // Donor Information View
        [HttpGet]
        public IActionResult DonorInfo(int id)
        {
            string check_Session = GetSession();
            if (check_Session == null || check_Session == "")
            {
                TempData["errorMsg"] = "Unauthorized Login to Continue";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                // DonorUpdate Failed then return 0
                if (id == 0)
                {
                    return RedirectToAction("ErrorPage", "Dashboard");
                }

                // Else
                try
                {
                    // Donor Data
                    var donorData = httpClient.GetStringAsync(basePath + "getDonor/" + id.ToString()).Result;
                    dynamic jsonObj = JsonConvert.DeserializeObject(donorData);

                    ViewData["donor_id"] = (int)jsonObj[0]["donor_id"];
                    ViewData["firstname"] = (string)jsonObj[0]["firstname"];
                    ViewData["lastname"] = (string)jsonObj[0]["lastname"];
                    ViewData["blood_type"] = (string)jsonObj[0]["blood_type"];
                    DateTime ldd = (DateTime)jsonObj[0]["last_date_donation"];
                    ViewData["last_date_donation"] = ldd.ToString("yyyy/MM/dd");
                    ViewData["gender"] = (string)jsonObj[0]["gender"];
                    DateTime dob = (DateTime)jsonObj[0]["dob"];
                    ViewData["dob"] = dob.ToString("yyyy/MM/dd");
                    ViewData["contact_number"] = (string)jsonObj[0]["contact_number"];
                    ViewData["city"] = (string)jsonObj[0]["city"];
                    ViewData["email_id"] = (string)jsonObj[0]["email_id"];
                    ViewData["address"] = (string)jsonObj[0]["address"];

                    return View();
                }
                catch
                {
                    return RedirectToAction("ErrorPage", "Dashboard");
                }
            }
        }

        // Update Donor on Submit from DonorInfo() View
        [HttpPost]
        public IActionResult DonorUpdate(int id, Donor donor)
        {
            string check_Session = GetSession();
            if (check_Session == null || check_Session == "")
            {
                TempData["errorMsg"] = "Unauthorized Login to Continue";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                try
                {
                    httpClient.BaseAddress = new Uri(basePath);
                    httpClient.DefaultRequestHeaders.Accept.Clear();
                    httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    //HTTP PUT
                    donor.donor_id = id; // Set Donor id
                    var stringContent = new StringContent(JsonConvert.SerializeObject(donor), Encoding.UTF8, "application/json");
                    var postTask = httpClient.PutAsync(basePath + "editDonor", stringContent);

                    var result = postTask.Result;
                    if (result.StatusCode == HttpStatusCode.OK)
                    {
                        TempData["msgHead"] = "Success";
                        TempData["msgBody"] = "Updated Donor Data to BoodBank...!";
                        return RedirectToAction("DonorInfo", "Dashboard", new { id = donor.donor_id });
                    }
                    else
                    {
                        TempData["msgHead"] = "Failed";
                        TempData["msgBody"] = "Unable to Update Donor Data...!";
                        return RedirectToAction("DonorInfo", "Dashboard", new { id = 0 });
                    }
                }
                catch
                {
                    return RedirectToAction("ErrorPage", "Dashboard");
                }
            }
        }

        // Delete Donor Data by ID from DonorInfo() View
        public IActionResult DonorDelete(int id)
        {
            string check_Session = GetSession();
            if (check_Session == null || check_Session == "")
            {
                TempData["errorMsg"] = "Unauthorized Login to Continue";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                try
                {
                    httpClient.BaseAddress = new Uri(basePath);
                    httpClient.DefaultRequestHeaders.Accept.Clear();

BloodBank1/Views/Dashboard/BloodDonorHistory.cshtml
@model List<DonorDonatedBlood>;

@{
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
    ViewData["Title"] = "BloodBank Blood Donor History";
}

<div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <i class="fa fa-caret-down fa-lg" aria-hidden="true"></i>
                    <span class="icon-bar"></span>
                </button>

                <button class="navbar-toggle btn-primary btn-lg" data-toggle="collapse" onclick="document.location='@Url.Action("Index", "BankBlood")'">
                    <i class="fa fa-tint" aria-hidden="true"></i> BloodBank2
                </button>

                <a class="navbar-brand logoimg" href="@Url.Action("Index", "Dashboard")">
                    <img src="~/assets/images/logo.png" alt="LOGO" style="width: 190px; height: 45px;">
                </a>
            </div>

            <div class="text-right collapse navbar-collapse" style="margin-top:10px;" id="myBtn">
                <a href="@Url.Action("Index", "BankBlood")" type="button" class="btn btn-lg btn-primary"><i class="fa fa-tint"></i> BloodBank2 Blood Stock Detail</a>
            </div>

            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <a href="@Url.Action("Index", "Dashboard")"><i class="fa fa-home"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="@Url.Action("BloodRequest", "Dashboard")"><i class="fa fa-tint"></i> Request Blood</a>
                    </li>
                    <li>
                        <a href="@Url.Action("NewDonor", "Dashboard")"><i class="fa fa-plus-square"></i> Add New Donor</a>
                    </li>
                    <li>
                        <a href="@Url.Action("BloodDonors", "Dashboard")"><i class="fa fa-user"></i> Blood Doners</a>
                    </li>
                    <li>
                        <a href="@Url.Action("BloodRecievers", "Dashboard")"><i class="fa fa-address-book"></i> Blood Recievers</a>
                    </li>
                    <li>
                        <a href="@Url.Action("BloodDetail", "Dashboard")"><i class="fa fa-eraser"></i> Blood Detail</a>
                    </li>
                    <li>
                        <a href="@Url.Action("DonationDetail", "Dashboard")"><i class="fa fa-users"></i> Donation Detail</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Logout", "Dashboard")"><i class="fa fa-sign-out"></i> Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- content -->
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row" id="main">
                <div class="col-lg-12 well" id="content">
                    <div class="row">

                        <div class="col-lg-4">
                            <h1 class="text-center">Donor Details</h1>

                            <div style="border: 1px solid #C5C2C2;">
                                <table class="table table-hover table-responsive-lg" id="donorTable">
                                    <tbody>
                                        <tr>
                                            <th>ID</th>
                                            <td>@ViewData["donor_id"]</td>
                                        </tr>
                                        <tr>
                                            <th>Full Name</th>
                                            <td>@ViewData["fullname"]</td>
                                        </tr>
                                        <tr>
                                            <th>Blood Type</th>
                                            <td>@ViewData["blood_type"]</td>
                                        </tr>
                                        <tr>
                                            <th>Last Date Donated</th>
                                            <td>@ViewData["last_date_donation"]</td>
                                        </tr>
                                        <tr>
                                            <th>Total Units Donated</th>
                                            <td>@ViewData["total_unit_donated"]</td>
                                        </tr>
                                        <tr>
                                            <th>Gender</th>
                                            <td>@ViewData["gender"]</td>
                                        </tr>
                                        <tr>
                                            <th>Date of Birth</th>
                                            <td>@ViewData["dob"]</td>
                                        </tr>
                                        <tr>
                                            <th>Contact #</th>
                                            <td>@ViewData["contact_number"]</td>
                                        </tr>
                                        <tr>
                                            <th>City</th>
                                            <td>@ViewData["city"]</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>

                            <div class="col-lg-12 text-center" style="margin-top:4px;">
                                <a class="btn btn-primary text-center" href="@Url.ActionLink("BloodDonors", "Dashboard")">Back To List</a>
                            </div>
                        </div>

                        <div class="col-lg-8">
                            <h1 class="text-center">Donated Blood Details</h1>
                            <h4 class="text-center"><strong>One unit of blood is ~525 mL, which is roughly the equivalent of one pint.</strong></h4>

                            <div style="overflow-x:auto;">
                                <!--Donor Blood History Table-->
                                <table class="table table-hover table-responsive-lg" id="bloodHistoryTable">
                                    <thead>
                                        <tr style="background-color: #F1F3FF; border:1px solid #CCCCCC;">
                                            <th class="text-center">ID</th>
                                            <th class="text-center">Units of Blood</th>
                                            <th class="text-center">Donation Date</th>
                                            <th class="text-center">Expiry Date</th>
                                            <th class="text-center">Consumed</th>
                                            <th class="text-center">Action</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            @if (@item.blood_id == 0)
                                            {
                                                <tr>
                                                    <td colspan="6">
                                                        <h4 class="text-center">No Donor Donation Data Found</h4>
                                                    </td>
                                                </tr>

                                                break;
                                            }

                                            <tr>
                                                <td class="text-center">@item.blood_id</td>
                                                <td class="text-center">@item.unit_of_blood</td>
                                                <td class="text-center">@item.date_donated.ToString("dd/MM/yyyy")</td>
                                                <td class="text-center">@item.expiry_date.ToString("dd/MM/yyyy")</td>
                                                @if (@item.CheckDonate == 0)
                                                {
                                                    <td class="text-center">No</td>
                                                }
                                                else
                                                {
                                                    <td class="text-center">Yes</td>

                                                }

                                                <td class="text-center">
                                                    <div class="btn-group" role="group">
                                                        <button id="@item.blood_id" type="button" class="btn btn-danger deleteBlood"><i class="fa fa-trash"></i> Remove</button>
                                                    </div>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Delete Donor Blood Data Modal-->
    <div class="modal fade" id="donorDeleteBloodModal" tabindex="-1" role="dialog" aria-labelledby="donorDeleteBloodModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title text-center">Confirm Delete</h3>
                </div>
                <form id="deleteForm" action="">
                    <div class="modal-body">
                        <table class="table table-borderless" hidden>
                            <tbody>
                                <tr>
                                    <th>
                                        <label for="blood_id">ID*</label>
                                    </th>
                                    <td>
                                        <input type="text" class="form-control" id="blood_id" value="1" disabled>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <h4 class="text-center">Are you Sure to Delete this Donor's Blood Record Permanently.</h4>
                        <h4 class="text-center"><strong>(May Effect Other Record)</strong></h4>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Delete Data</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

<script>
    $(document).ready(function () {
        // Datatable
        $('#bloodHistoryTable').DataTable({
            "pagingType": "full_numbers"
        });

        // Delete Modal
        $('#bloodHistoryTable tbody').on('click', '.deleteBlood', function () {
            var curr_row = $(this).closest('tr');
            var id = curr_row.find('td:eq(0)').text();

            // Add data to Modal
            $('#deleteForm').attr('action', '../DonorBloodDataDelete/' + id);
            $('#donorDeleteBloodModal').modal('show');
        });
    });
</script>

BloodBank1/Views/Dashboard/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
    ViewData["Title"] = "BloodBank Dashboard";
}

    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <i class="fa fa-caret-down fa-lg" aria-hidden="true"></i>
                        <span class="icon-bar"></span>
                    </button>

                    <button class="navbar-toggle btn-primary btn-lg" data-toggle="collapse" onclick="document.location='@Url.Action("Index", "BankBlood")'">
                        <i class="fa fa-tint" aria-hidden="true"></i> BloodBank2
                    </button>

                    <a class="navbar-brand logoimg" href="@Url.Action("Index", "Dashboard")">
                        <img src="~/assets/images/logo.png" alt="LOGO" style="width: 190px; height: 45px;">
                    </a>
                </div>

                <div class="text-right collapse navbar-collapse" style="margin-top:10px;" id="myBtn">
                    <a href="@Url.Action("Index", "BankBlood")" type="button" class="btn btn-lg btn-primary"><i class="fa fa-tint"></i> BloodBank2 Blood Stock Detail</a>
                </div>

                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav side-nav">
                        <li>
                            <a href="@Url.Action("Index", "Dashboard")"><i class="fa fa-home"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="@Url.Action("BloodRequest", "Dashboard")"><i class="fa fa-tint"></i> Request Blood</a>
                        </li>
                        <li>
                            <a href="@Url.Action("NewDonor", "Dashboard")"><i class="fa fa-plus-square"></i> Add New Donor</a>
                        </li>
                        <li>
                            <a href="@Url.Action("BloodDonors", "Dashboard")"><i class="fa fa-user"></i> Blood Doners</a>
                        </li>
                        <li>
                            <a href="@Url.Action("BloodRecievers", "Dashboard")"><i class="fa fa-address-book"></i> Blood Recievers</a>
                        </li>
                        <li>
                            <a href="@Url.Action("BloodDetail", "Dashboard")"><i class="fa fa-eraser"></i> Blood Detail</a>
                        </li>
                        <li>
                            <a href="@Url.Action("DonationDetail", "Dashboard")"><i class="fa fa-users"></i> Donation Detail</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Logout", "Dashboard")"><i class="fa fa-sign-out"></i> Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <!-- content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row" id="main">
                    <div class="col-sm-12 col-md-12 well" id="content">
                        <h1 class="text-center display-3">Welcome Admin!</h1>
                        <h1 class="text-center display-3">@ViewData["Session"]</h1>
                        <h3 class="text-center">Total Units of Blood Available : <span id="total_blood">@ViewData["total_blood"]</span></h3>
                        <h4 class="text-center"><strong>One unit of blood is ~525 mL, which is roughly the equivalent of one pint.</strong></h4>
                    </div>
                    <br />

                    <div class="col-sm-3 col-md-3 well" id="content">
                        <h3 class="text-center display-4">O Positive</h3>
                        <h1 class="text-center" id="op">@ViewData["O+"]</h1>
                    </div>
                    <div class="col-sm-3 col-md-3 well" id="content">
                        <h3 class="text-center display-4">O Negative</h3>
                        <h1 class="text-center" id="on">@ViewData["O-"]</h1>
                    </div>

                    <div class="col-sm-3 col-md-3 well" id="content">
                        <h3 class="text-center display-4">A Positive</h3>
                        <h1 class="text-center" id="ap">@ViewData["A+"]</h1>
                    </div>
                    <div class="col-sm-3 col-md-3 well" id="content">
                        <h3 class="text-center display-4">A Negative</h3>
                        <h1 class="text-center" id="an">@ViewData["A-"]</h1>
                    </div>

                    <div class="col-sm-3 col-md-3 well" id="content">
                        <h3 class="text-center display-4">B Positive</h3>
                        <h1 class="text-center" id="bp">@ViewData["B+"]</h1>
                    </div>
                    <div class="col-sm-3 col-md-3 well" id="content">
                        <h3 class="text-center display-4">B Negative</h3>
                        <h1 class="text-center" id="bn">@ViewData["B-"]</h1>
                    </div>

                    <div class="col-sm-3 col-md-3 well" id="content">
                        <h3 class="text-center display-4">AB Positive</h3>
                        <h1 class="text-center" id="abp">@ViewData["AB+"]</h1>
                    </div>
                    <div class="col-sm-3 col-md-3 well" id="content">
                        <h3 class="text-center display-4">AB Negative</h3>
                        <h1 class="text-center" id="abn">@ViewData["AB-"]</h1>
                    </div>
                </div>
            </div>
        </div>

    </div>